name: Author Lines

on:
  push:
  pull_request:

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

jobs:
  Author_Lines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Author line of files
        run: python .github/scripts/Author_Checker.py
